apiVersion: v1
kind: Service
metadata:
  name: {{ include "enemy-territory.fullname" . }}
  labels:
    {{- include "enemy-territory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: UDP
      name: http
  selector:
    {{- include "enemy-territory.selectorLabels" . | nindent 4 }}
