apiVersion: v1
kind: Service
metadata:
  name: {{ include "enemy-territory.fullname" . }}
  labels:
    {{- include "enemy-territory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "enemy-territory.selectorLabels" . | nindent 4 }}
