---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.fullname" . }}
data:
  config.yml: |
    tunnel: {{ .Values.cloudflared.tunnelID }}
    credentials-file: /etc/cloudflared/credential.json
    ingress:
    {{- with .Values.cloudflared.ingress }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
