{{- if not .Values.cloudflared.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "cloudflared.fullname" . }}
type: Opaque
data:
    credential.json: |
      {{ .Values.cloudflared.credentials | b64enc }}
{{- end -}}
